# Generated by Django 4.2.4 on 2023-08-28 16:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignUpModel',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('UserUUID', models.UUIDField()),
                ('SignUpName', models.CharField(max_length=255)),
                ('SignUpEmail', models.CharField(max_length=255, unique=True)),
                ('SignUpNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('SignUpPassword', models.CharField(max_length=500)),
            ],
        ),
    ]
