# Generated by Django 4.2.4 on 2023-08-28 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignupmodel',
            name='UserUUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
