# Generated by Django 4.2.4 on 2023-08-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_usersignupmodel_useruuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignupmodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
