# Generated by Django 4.2.4 on 2023-09-02 13:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_usersignupmodel_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksModel',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('UserUUID', models.CharField(max_length=255)),
                ('TaskName', models.CharField(max_length=255)),
                ('TaskAddedOn', models.CharField(max_length=255, unique=True)),
                ('TaskDeadline', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('IsCompleted', models.CharField(max_length=500)),
            ],
        ),
    ]
