# Generated by Django 4.2.4 on 2023-09-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_tasksmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksmodel',
            old_name='_id',
            new_name='task_id',
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='IsCompleted',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='TaskAddedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='TaskDeadline',
            field=models.DateTimeField(),
        ),
    ]
