# Generated by Django 4.2.4 on 2024-05-24 18:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_rename__id_tasksmodel_task_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksmodel',
            old_name='IsCompleted',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='tasksmodel',
            old_name='TaskAddedOn',
            new_name='task_added_on',
        ),
        migrations.RenameField(
            model_name='tasksmodel',
            old_name='TaskDeadline',
            new_name='task_deadline',
        ),
        migrations.RenameField(
            model_name='tasksmodel',
            old_name='TaskName',
            new_name='task_name',
        ),
        migrations.RenameField(
            model_name='tasksmodel',
            old_name='UserUUID',
            new_name='user_uuid',
        ),
        migrations.RenameField(
            model_name='usersignupmodel',
            old_name='SignUpEmail',
            new_name='signup_email',
        ),
        migrations.RenameField(
            model_name='usersignupmodel',
            old_name='SignUpName',
            new_name='signup_name',
        ),
        migrations.RenameField(
            model_name='usersignupmodel',
            old_name='SignUpPassword',
            new_name='signup_password',
        ),
        migrations.RenameField(
            model_name='usersignupmodel',
            old_name='UserUUID',
            new_name='user_uuid',
        ),
        migrations.RemoveField(
            model_name='usersignupmodel',
            name='SignUpNumber',
        ),
        migrations.AddField(
            model_name='usersignupmodel',
            name='signup_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
