# Generated by Django 4.2.4 on 2024-05-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_rename_iscompleted_tasksmodel_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
